# Generated by Django 5.1.2 on 2024-10-24 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_alter_pacientesmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompanhamento_medico', models.CharField(blank=True, default='Não faz', max_length=100)),
                ('medicamento_em_uso', models.CharField(blank=True, default='Não faz', max_length=200)),
                ('diabetico', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='n', max_length=1)),
                ('hepatite', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='n', max_length=1)),
                ('hiv', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='n', max_length=1)),
                ('alergico', models.CharField(default='Nenhuma', max_length=50)),
                ('teve_cancer', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='n', max_length=1)),
                ('gravidez', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='n', max_length=1)),
                ('lactante', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='n', max_length=1)),
                ('hipertensao', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='n', max_length=1)),
                ('hipotensao', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='n', max_length=1)),
                ('observacoes', models.TextField(blank=True, max_length=400)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='pacientes.pacientesmodel')),
            ],
            options={
                'db_table': 'anamnese',
            },
        ),
    ]
