# Generated by Django 5.1.2 on 2024-10-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='diabetico',
            field=models.CharField(choices=[('Não', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='gravidez',
            field=models.CharField(choices=[('Não', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='hepatite',
            field=models.CharField(choices=[('Não', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='hipertensao',
            field=models.CharField(choices=[('Não', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='hipotensao',
            field=models.CharField(choices=[('Não', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='hiv',
            field=models.CharField(choices=[('Não', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='lactante',
            field=models.CharField(choices=[('Não', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='teve_cancer',
            field=models.CharField(choices=[('Não', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
