# Generated by Django 5.1.2 on 2024-10-25 00:49

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0002_alter_anamnesemodel_diabetico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamnesemodel',
            options={'verbose_name_plural': 'Anamneses'},
        ),
        migrations.AddField(
            model_name='anamnesemodel',
            name='data',
            field=models.DateField(),
        ),
    ]
