# Generated by Django 5.1.2 on 2024-10-25 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0003_alter_anamnesemodel_options_anamnesemodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 10, 24, 21, 53, 23, 444430)),
        ),
    ]
