# Generated by Django 5.1.2 on 2024-10-25 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0005_alter_anamnesemodel_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnesemodel',
            old_name='alergico',
            new_name='alergia',
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='data',
            field=models.DateField(default=datetime.date(2024, 10, 25)),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='diabetico',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='gravidez',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='hepatite',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='hipertensao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='hipotensao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='hiv',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='lactante',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='teve_cancer',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
