# Generated by Django 5.1.2 on 2024-10-25 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0006_rename_alergico_anamnesemodel_alergia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='anamnesemodel',
            table='anamneses',
        ),
    ]
