# Generated by Django 5.1.2 on 2024-11-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0007_alter_anamnesemodel_data_alter_anamnesemodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='acompanhamento_medico',
            field=models.CharField(blank=True, default='Não faz', max_length=60),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='medicamento_em_uso',
            field=models.CharField(blank=True, default='Não faz', max_length=60),
        ),
    ]
