# Generated by Django 5.1.2 on 2024-10-24 23:00

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientesmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pacientesmodel',
            name='primeiro_atendimento',
            field=models.DateField(default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='pacientesmodel',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
