# Generated by Django 5.1.2 on 2024-10-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_pacientesmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientesmodel',
            options={'verbose_name_plural': 'Pacientes'},
        ),
    ]
