# Generated by Django 5.1.2 on 2024-10-25 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DespesasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('fornecedor', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('total', models.FloatField()),
                ('pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Credito', 'Crédito'), ('Debito', 'Débito'), ('Dinheiro', 'Dinheiro')], max_length=20)),
                ('observacoes', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Despesas',
                'db_table': 'despesas',
            },
        ),
    ]
